### ISSUE TITLE
Fix nonce +1 / nonce +2 issue with check or README 

### ISSUE THREAD

**Issue by musnit** [Snowfork/BTRST-Contracts#21]

**Comment by aimanafzal** [comment]
Can anyone contribute to this project? @musnit

**Comment by aimanafzal** [comment]
@musnit I would love to be a contributor to BTRST. Have been following it for long time. 
Can you add more issues so that I can start resolving those.

**Comment by musnit** [comment]
@aimanafzal The contracts and token are all now deployed and so there are no real outstanding issues. You can join https://discord.gg/ykz3Pr2A to get more involved in the discussion and chat to others about future roadmap ideas for governance and the token to work out how you can help :)!
